import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("day14/business_data.csv")
# print(df)

#pandas
'''
How much sales revenue has been generated by each product category? and which has the highest value?
'''


df["Category"]=df["Category"].astype("string")

df["Category"] = df["Category"].str.strip() #remove leading/trailing spaces

df["Category"] = df["Category"].str.title()

df["Category"]=df["Category"].replace({"I.T.":"IT","It":"IT","Information Technology":"IT"})

#clean total_amount column
df["Total_Amount"] = pd.to_numeric(df["Total_Amount"],errors="coerce") #coerce means ignore errors #convert to numeric, set errors to NaN

#remove missing values:
df=df.dropna(subset=["Category","Total_Amount"]) #drop rows where Category or Total_Amount is missing

#check cleaned categories values:
print("\nCleaned Category Values:")
print(df["Category"].value_counts())

#group sales by categories:
category_sales =df.groupby("Category")["Total_Amount"].sum()
print("\nCategory sales: ")
print(category_sales)

#convert pandas data to numpy arrays:
categories = category_sales.index.to_numpy()
sales = category_sales.to_numpy()

#numpy analysis
total_sales = np.sum(sales)
print("\nTotal Sales:",total_sales)

avg_sales = np.average(sales)
print("\nAverage Sales:",avg_sales)

highest_sales = np.max(sales)
print("\nHighest Sales:",highest_sales)

highest_index = np.argmax(sales)
print("\nHighest Sales Index:",highest_index)

highest_category = categories[highest_index]
print("\nHighest Sales Category:",highest_category)



#work with the selected columns
sales_data=df[["Category","Total_Amount"]]
# print(sales_data.head())




sales_data = sales_data.dropna(subset=["Category","Total_Amount"])
print(sales_data.head())

category_sales= sales_data.groupby("Category")["Total_Amount"].sum()
print(category_sales)




#numpy-convert to numpy arrays for further analysis

categories= category_sales.index.to_numpy()
sales= category_sales.to_numpy()

total_sales=np.sum(sales)
print("Total Sales",total_sales)

avg_sales=np.average(sales)
print("Average Sales",avg_sales)

highest_sales=np.max(sales)
print("Highest Sales",highest_sales)

highest_index = np.argmax(sales)
print("Highest Sales Index",highest_index)

highest_category = categories[highest_index]
print("Highest Sales Category",highest_category)


#matplotlib
plt.bar(categories,sales)
plt.xlabel("Categories")
plt.ylabel("Sales")
plt.xticks(rotation=90)
plt.tight_layout()
plt.title("Sales by Category")
plt.show()









